[package]
name = "code-finder"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
code_finder_macros = { path = "code_finder_macros" }
once_cell = "1.0"
shebling_macros = { workspace = true }
