[package]
name = "introspector_macro_helpers"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { workspace = true, features = ["full", "extra-traits", "parsing"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
